/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee.ospedale.view;

import packagee.ospedale.controller.DoctorController;
import packagee.ospedale.controller.PatientController;
import packagee.ospedale.controller.utils.Response;
import packagee.ospedale.controller.utils.Status;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class Admin_View extends javax.swing.JFrame {

    private int x, y;

public Admin_View() {
    initComponents();
    this.setBackground(new Color(0, 0, 0, 0));
    this.setLocationRelativeTo(null);
    loadDoctorsComboBox();
    loadPatientsComboBox();
}

private void loadDoctorsComboBox() {
    Response response = DoctorController.getAllDoctors();
    if (response.getStatus() == Status.OK) {
        select_doctor.removeAllItems();
        ArrayList<java.util.HashMap<String, Object>> doctors =
                (ArrayList<java.util.HashMap<String, Object>>) response.getData().get("doctors");
        for (java.util.HashMap<String, Object> d : doctors) {
            select_doctor.addItem("" + d.get("id"));
        }
    }
}

private void loadPatientsComboBox() {
    Response response = PatientController.getAllPatients();
    if (response.getStatus() == Status.OK) {
        select_patient.removeAllItems();
        ArrayList<java.util.HashMap<String, Object>> patients =
                (ArrayList<java.util.HashMap<String, Object>>) response.getData().get("patients");
        for (java.util.HashMap<String, Object> p : patients) {
            select_patient.addItem("" + p.get("id"));
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new packagee.ospedale.view.PanelRound();
        panel2 = new packagee.ospedale.view.PanelRound();
        x_logout = new javax.swing.JButton();
        admin_view_label = new javax.swing.JLabel();
        panel3 = new packagee.ospedale.view.PanelRound();
        doctor_view_button = new javax.swing.JButton();
        patient_view_button = new javax.swing.JButton();
        firstname_label = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        last_name_label = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        id_label = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        specialty_label = new javax.swing.JLabel();
        license_numer_label = new javax.swing.JLabel();
        license_number = new javax.swing.JTextField();
        office_label = new javax.swing.JLabel();
        assigned_office = new javax.swing.JTextField();
        user_label = new javax.swing.JLabel();
        user_admin = new javax.swing.JTextField();
        password_label = new javax.swing.JLabel();
        password_admin = new javax.swing.JTextField();
        confirmation_label = new javax.swing.JLabel();
        password_confirmation_admin = new javax.swing.JTextField();
        specialty = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        select_doctor = new javax.swing.JComboBox<>();
        doctor_label = new javax.swing.JLabel();
        patient_label = new javax.swing.JLabel();
        select_patient = new javax.swing.JComboBox<>();
        separator_2 = new javax.swing.JSeparator();
        logout_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel1.setRadius(50);

        panel2.setRadius(50);
        panel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel2MouseDragged(evt);
            }
        });
        panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel2MousePressed(evt);
            }
        });

        x_logout.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        x_logout.setText("X");
        x_logout.setBorderPainted(false);
        x_logout.setContentAreaFilled(false);
        x_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        x_logout.setFocusable(false);
        x_logout.setRequestFocusEnabled(false);
        x_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_logoutActionPerformed(evt);
            }
        });

        admin_view_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        admin_view_label.setText("ADMIN VIEW");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(admin_view_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(x_logout)
                .addGap(19, 19, 19))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(x_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(admin_view_label))
        );

        doctor_view_button.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        doctor_view_button.setText("DOCTOR VIEW");
        doctor_view_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctor_view_buttonActionPerformed(evt);
            }
        });

        patient_view_button.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        patient_view_button.setText("PATIENT VIEW");
        patient_view_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_view_buttonActionPerformed(evt);
            }
        });

        firstname_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        firstname_label.setText("Firstname");

        first_name.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        last_name_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        last_name_label.setText("Lastname");

        last_name.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        id_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        id_label.setText("ID");

        id.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        specialty_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        specialty_label.setText("Specialty");

        license_numer_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        license_numer_label.setText("License Number");

        license_number.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        office_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        office_label.setText("Assigned office");

        assigned_office.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        user_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        user_label.setText("User");

        user_admin.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        password_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        password_label.setText("Password");

        password_admin.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        confirmation_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        confirmation_label.setText("Password confirmation");

        password_confirmation_admin.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        specialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        specialty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        jButton9.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jButton9.setText("Save");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        select_doctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        select_doctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        doctor_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        doctor_label.setText("Doctor");

        patient_label.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        patient_label.setText("Patient");

        select_patient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        select_patient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        separator_2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        logout_button.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        logout_button.setText("Logout");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstname_label)
                                    .addComponent(specialty_label))
                                .addGap(18, 18, 18)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addComponent(specialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(license_numer_label)
                                        .addGap(18, 18, 18)
                                        .addComponent(license_number, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(last_name_label)
                                        .addGap(18, 18, 18)
                                        .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(id_label)
                                        .addGap(18, 18, 18)
                                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(office_label)
                                .addGap(18, 18, 18)
                                .addComponent(assigned_office, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panel3Layout.createSequentialGroup()
                                    .addComponent(user_label)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(user_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel3Layout.createSequentialGroup()
                                    .addComponent(password_label)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(password_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel3Layout.createSequentialGroup()
                                    .addComponent(confirmation_label)
                                    .addGap(18, 18, 18)
                                    .addComponent(password_confirmation_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctor_view_button)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(select_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(doctor_label)))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout_button)
                        .addGap(318, 318, 318)))
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patient_view_button)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(select_patient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(patient_label)))
                .addGap(88, 88, 88))
            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                    .addContainerGap(707, Short.MAX_VALUE)
                    .addComponent(separator_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(523, 523, 523)))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addComponent(separator)
                .addContainerGap())
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname_label)
                    .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_name_label)
                    .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_label)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(specialty_label)
                    .addComponent(specialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(license_numer_label)
                    .addComponent(license_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(office_label)
                    .addComponent(assigned_office, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user_label)
                            .addComponent(user_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password_label)
                            .addComponent(password_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmation_label)
                            .addComponent(password_confirmation_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(doctor_label)
                        .addGap(18, 18, 18)
                        .addComponent(select_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(doctor_view_button)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(123, 123, 123)
                .addComponent(logout_button)
                .addGap(38, 38, 38))
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(patient_label)
                .addGap(18, 18, 18)
                .addComponent(select_patient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(patient_view_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(separator_2)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panel2MousePressed

    private void panel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panel2MouseDragged

    private void x_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_logoutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_x_logoutActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String id_str = id.getText();
        String username = user_admin.getText();
        String password = password_admin.getText();
        String confirmPassword = password_confirmation_admin.getText();
        String firstname = first_name.getText();
        String lastname = last_name.getText();
        String licence = license_number.getText();
        String office = assigned_office.getText();
        String spec = (String) specialty.getSelectedItem();

        Response response = DoctorController.registerDoctor(id_str, username, password, confirmPassword, firstname, lastname, licence, office, spec);

        if (response.getStatus() >= 500) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.ERROR_MESSAGE);
        } else if (response.getStatus() >= 400) {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Error " + response.getStatus(), JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, response.getMessage(), "Response Message", JOptionPane.INFORMATION_MESSAGE);
            id.setText("");
            user_admin.setText("");
            password_admin.setText("");
            password_confirmation_admin.setText("");
            first_name.setText("");
            last_name.setText("");
            license_number.setText("");
            assigned_office.setText("");
            specialty.setSelectedIndex(0);
            loadDoctorsComboBox();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void doctor_view_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctor_view_buttonActionPerformed
        String selectedId = (String) select_doctor.getSelectedItem();
        if (selectedId == null) {
            JOptionPane.showMessageDialog(null, "Please select a doctor", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        long doctorId = Long.parseLong(selectedId);
        Doctor_View doctor = new Doctor_View(doctorId, true);
        this.setVisible(false);
        doctor.setVisible(true);
    }//GEN-LAST:event_doctor_view_buttonActionPerformed

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        
        Login login = new Login();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void patient_view_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_view_buttonActionPerformed
        String selectedId = (String) select_patient.getSelectedItem();
        if (selectedId == null) {
            JOptionPane.showMessageDialog(null, "Please select a patient", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        long patientId = Long.parseLong(selectedId);
        Patient_View patient = new Patient_View(patientId, true);
        this.setVisible(false);
        patient.setVisible(true);
    }//GEN-LAST:event_patient_view_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin_view_label;
    private javax.swing.JTextField assigned_office;
    private javax.swing.JLabel confirmation_label;
    private javax.swing.JLabel doctor_label;
    private javax.swing.JButton doctor_view_button;
    private javax.swing.JTextField first_name;
    private javax.swing.JLabel firstname_label;
    private javax.swing.JTextField id;
    private javax.swing.JLabel id_label;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField last_name;
    private javax.swing.JLabel last_name_label;
    private javax.swing.JTextField license_number;
    private javax.swing.JLabel license_numer_label;
    private javax.swing.JButton logout_button;
    private javax.swing.JLabel office_label;
    private packagee.ospedale.view.PanelRound panel1;
    private packagee.ospedale.view.PanelRound panel2;
    private packagee.ospedale.view.PanelRound panel3;
    private javax.swing.JTextField password_admin;
    private javax.swing.JTextField password_confirmation_admin;
    private javax.swing.JLabel password_label;
    private javax.swing.JLabel patient_label;
    private javax.swing.JButton patient_view_button;
    private javax.swing.JComboBox<String> select_doctor;
    private javax.swing.JComboBox<String> select_patient;
    private javax.swing.JSeparator separator;
    private javax.swing.JSeparator separator_2;
    private javax.swing.JComboBox<String> specialty;
    private javax.swing.JLabel specialty_label;
    private javax.swing.JTextField user_admin;
    private javax.swing.JLabel user_label;
    private javax.swing.JButton x_logout;
    // End of variables declaration//GEN-END:variables
}
