/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee.ospedale.view;

import java.awt.Color;
import javax.swing.JOptionPane;
import packagee.ospedale.controller.PatientController;
import packagee.ospedale.controller.AuthController;
import packagee.ospedale.controller.utils.Response;

/**
 * Pantalla inicial para autenticacion y registro de pacientes.
 */
public class Login extends javax.swing.JFrame {

    private int x, y;

    public Login() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    // Centraliza la presentacion de mensajes para mantener la vista consistente.
    private void showResponse(Response response) {

        if (response.getStatus() >= 500) {

            JOptionPane.showMessageDialog(
                    null,
                    response.getMessage(),
                    "Error " + response.getStatus(),
                    JOptionPane.ERROR_MESSAGE
            );

        } else if (response.getStatus() >= 400) {

            JOptionPane.showMessageDialog(
                    null,
                    response.getMessage(),
                    "Error " + response.getStatus(),
                    JOptionPane.WARNING_MESSAGE
            );

        } else {

            JOptionPane.showMessageDialog(
                    null,
                    response.getMessage(),
                    "Response Message",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new packagee.ospedale.view.PanelRound();
        panelRound2 = new packagee.ospedale.view.PanelRound();
        exit_button = new javax.swing.JButton();
        view = new javax.swing.JTabbedPane();
        login_view = new packagee.ospedale.view.PanelRound();
        lblTitleLogin = new javax.swing.JLabel();
        username_login_input = new javax.swing.JTextField();
        lblUsernName = new javax.swing.JLabel();
        password_login_input = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        enter_login1 = new javax.swing.JButton();
        patient_register_view = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        firstname_patient_register = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        last_name_patient_register = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        id_patient_register = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        phone_patient_register = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        email_patient_register = new javax.swing.JTextField();
        lblUserPatientRegister = new javax.swing.JLabel();
        user_patient_register = new javax.swing.JTextField();
        password_patient_register = new javax.swing.JTextField();
        lblPasswordRegister = new javax.swing.JLabel();
        lblPasswordConfirmationPatientRegister = new javax.swing.JLabel();
        password_confirmation_patient_register = new javax.swing.JTextField();
        select_gender = new javax.swing.JComboBox<>();
        save_patient_register = new javax.swing.JButton();
        lblAddress = new javax.swing.JLabel();
        address_patient_register = new javax.swing.JTextField();
        lblBirthdate = new javax.swing.JLabel();
        birthdate_patient_register = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelRound1.setRadius(50);

        panelRound2.setRadius(50);
        panelRound2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        panelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        exit_button.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        exit_button.setText("X");
        exit_button.setBorderPainted(false);
        exit_button.setContentAreaFilled(false);
        exit_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit_button.setFocusable(false);
        exit_button.setRequestFocusEnabled(false);
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit_button)
                .addGap(19, 19, 19))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblTitleLogin.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblTitleLogin.setText("LOGIN");

        username_login_input.setFont(new java.awt.Font("Yu Gothic UI", 0, 18));
        username_login_input.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblUsernName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblUsernName.setText("USERNAME");

        password_login_input.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        password_login_input.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPassword.setText("PASSWORD");

        enter_login1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18));
        enter_login1.setText("ENTER");
        enter_login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_login1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout login_viewLayout = new javax.swing.GroupLayout(login_view);
        login_view.setLayout(login_viewLayout);
        login_viewLayout.setHorizontalGroup(
            login_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_viewLayout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(lblTitleLogin)
                .addGap(481, 481, 481))
            .addGroup(login_viewLayout.createSequentialGroup()
                .addGroup(login_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(login_viewLayout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(login_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_viewLayout.createSequentialGroup()
                                .addGroup(login_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblUsernName, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(password_login_input, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(username_login_input, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(login_viewLayout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(enter_login1)))
                .addContainerGap(445, Short.MAX_VALUE))
        );
        login_viewLayout.setVerticalGroup(
            login_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_viewLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblTitleLogin)
                .addGap(74, 74, 74)
                .addComponent(lblUsernName)
                .addGap(18, 18, 18)
                .addComponent(username_login_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addGap(18, 18, 18)
                .addComponent(password_login_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(enter_login1)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        view.addTab("Login", login_view);

        lblFirstName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblFirstName.setText("Firstname");

        firstname_patient_register.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblLastName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLastName.setText("Lastname");

        last_name_patient_register.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblId.setText("ID");

        id_patient_register.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblGender.setText("Gender");

        lblPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPhone.setText("Phone");

        phone_patient_register.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblEmail.setText("Email");

        email_patient_register.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblUserPatientRegister.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblUserPatientRegister.setText("User");

        user_patient_register.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        password_patient_register.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblPasswordRegister.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPasswordRegister.setText("Password");

        lblPasswordConfirmationPatientRegister.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblPasswordConfirmationPatientRegister.setText("Password confirmation");

        password_confirmation_patient_register.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        password_confirmation_patient_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_confirmation_patient_registerActionPerformed(evt);
            }
        });

        select_gender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        select_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        save_patient_register.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        save_patient_register.setText("Save");
        save_patient_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_patient_registerActionPerformed(evt);
            }
        });

        lblAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblAddress.setText("Address");

        address_patient_register.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblBirthdate.setText("Birthdate");

        birthdate_patient_register.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout patient_register_viewLayout = new javax.swing.GroupLayout(patient_register_view);
        patient_register_view.setLayout(patient_register_viewLayout);
        patient_register_viewLayout.setHorizontalGroup(
            patient_register_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patient_register_viewLayout.createSequentialGroup()
                .addGroup(patient_register_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patient_register_viewLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(lblPasswordRegister))
                    .addGroup(patient_register_viewLayout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(patient_register_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(patient_register_viewLayout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(lblUserPatientRegister))
                    .addGroup(patient_register_viewLayout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(password_confirmation_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(patient_register_viewLayout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(save_patient_register))
                    .addGroup(patient_register_viewLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(lblPasswordConfirmationPatientRegister))
                    .addGroup(patient_register_viewLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(patient_register_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(patient_register_viewLayout.createSequentialGroup()
                                .addComponent(lblBirthdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(birthdate_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(patient_register_viewLayout.createSequentialGroup()
                                .addComponent(lblFirstName)
                                .addGap(34, 34, 34)
                                .addComponent(firstname_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(patient_register_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLastName)
                            .addComponent(lblAddress))
                        .addGap(18, 18, 18)
                        .addGroup(patient_register_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(patient_register_viewLayout.createSequentialGroup()
                                .addComponent(last_name_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblId)
                                .addGap(30, 30, 30)
                                .addComponent(id_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblGender)
                                .addGap(26, 26, 26)
                                .addComponent(select_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(patient_register_viewLayout.createSequentialGroup()
                                .addComponent(address_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPhone)
                                .addGap(18, 18, 18)
                                .addComponent(phone_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEmail)
                                .addGap(18, 18, 18)
                                .addComponent(email_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        patient_register_viewLayout.setVerticalGroup(
            patient_register_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patient_register_viewLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(patient_register_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(firstname_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName)
                    .addComponent(last_name_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId)
                    .addComponent(id_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender)
                    .addComponent(select_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(patient_register_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patient_register_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBirthdate)
                        .addComponent(birthdate_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAddress)
                        .addComponent(address_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPhone)
                        .addComponent(phone_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(patient_register_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail)
                        .addComponent(email_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(lblUserPatientRegister)
                .addGap(18, 18, 18)
                .addComponent(user_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPasswordRegister)
                .addGap(18, 18, 18)
                .addComponent(password_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPasswordConfirmationPatientRegister)
                .addGap(18, 18, 18)
                .addComponent(password_confirmation_patient_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(save_patient_register)
                .addGap(42, 42, 42))
        );

        view.addTab("Patient register", patient_register_view);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void clearPatientRegisterFields() {

        id_patient_register.setText("");
        user_patient_register.setText("");
        password_patient_register.setText("");
        password_confirmation_patient_register.setText("");
        firstname_patient_register.setText("");
        last_name_patient_register.setText("");
        email_patient_register.setText("");
        birthdate_patient_register.setText("");
        phone_patient_register.setText("");
        address_patient_register.setText("");
        select_gender.setSelectedIndex(0);
    }
    
    private void clearLoginFields() {

        username_login_input.setText("");
        password_login_input.setText("");
    }

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_buttonActionPerformed

    
    private void save_patient_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_patient_registerActionPerformed
        String id = id_patient_register.getText();
        String username = user_patient_register.getText();
        String password = password_patient_register.getText();
        String confirmPassword = password_confirmation_patient_register.getText();
        String firstname = firstname_patient_register.getText();
        String lastname = last_name_patient_register.getText();
        String email = email_patient_register.getText();
        String birthdate = birthdate_patient_register.getText();
        String gender = (String) select_gender.getSelectedItem();
        String phone = phone_patient_register.getText();
        String address = address_patient_register.getText();

        Response response = PatientController.registerPatient(
                id,
                username,
                password,
                confirmPassword,
                firstname,
                lastname,
                email,
                birthdate,
                gender,
                phone,
                address
        );

        showResponse(response);

        if (response.getStatus() < 400) {
            clearPatientRegisterFields();
        }
        
        
    }//GEN-LAST:event_save_patient_registerActionPerformed

    private void password_confirmation_patient_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_confirmation_patient_registerActionPerformed
    }//GEN-LAST:event_password_confirmation_patient_registerActionPerformed

    private void enter_login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_login1ActionPerformed
        String username = username_login_input.getText();
        String password = password_login_input.getText();

        Response response = AuthController.login(username, password);

        showResponse(response);

        if (response.getStatus() < 400) {

            String role = (String) response.getData().get("role");
            long id = (long) response.getData().get("id");

            if (role.equals("admin")) {

                Admin_View admin = new Admin_View();
                admin.setVisible(true);
                dispose();

            } else if (role.equals("doctor")) {

                Doctor_View doctor = new Doctor_View(id, false);
                doctor.setVisible(true);
                dispose();

            } else {

                Patient_View patient = new Patient_View(id, false);
                patient.setVisible(true);
                dispose();
            }

            clearLoginFields();
        }
    }//GEN-LAST:event_enter_login1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_patient_register;
    private javax.swing.JTextField birthdate_patient_register;
    private javax.swing.JTextField email_patient_register;
    private javax.swing.JButton enter_login1;
    private javax.swing.JButton exit_button;
    private javax.swing.JTextField firstname_patient_register;
    private javax.swing.JTextField id_patient_register;
    private javax.swing.JTextField last_name_patient_register;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBirthdate;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordConfirmationPatientRegister;
    private javax.swing.JLabel lblPasswordRegister;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblTitleLogin;
    private javax.swing.JLabel lblUserPatientRegister;
    private javax.swing.JLabel lblUsernName;
    private packagee.ospedale.view.PanelRound login_view;
    private packagee.ospedale.view.PanelRound panelRound1;
    private packagee.ospedale.view.PanelRound panelRound2;
    private javax.swing.JTextField password_confirmation_patient_register;
    private javax.swing.JTextField password_login_input;
    private javax.swing.JTextField password_patient_register;
    private javax.swing.JPanel patient_register_view;
    private javax.swing.JTextField phone_patient_register;
    private javax.swing.JButton save_patient_register;
    private javax.swing.JComboBox<String> select_gender;
    private javax.swing.JTextField user_patient_register;
    private javax.swing.JTextField username_login_input;
    private javax.swing.JTabbedPane view;
    // End of variables declaration//GEN-END:variables
}
